import { Inter } from 'next/font/google'
import './globals.css'
import { sans, roboto_mono, satisfy, kalam, cabin } from "../app/styles/fonts";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'tracktoceylon',
  description: 'Generated by create next app',
  icons: {
    icon: 'public/icon.ico', 
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white ${sans.className} ${roboto_mono.variable} ${satisfy.variable} ${kalam.variable} ${cabin.variable}`}>{children}</body>
    </html>
  )
}
